controllers/ArticleController.php
<?php


namespace app\controllers;


use app\helpers\Request;
use app\models\ar\Article;
use app\models\ar\ArticleQuery;
use app\models\ar\Category;
use app\models\ar\Tag;
use app\models\ar\Type;
use Yii;
use yii\web\Controller;

class ArticleController extends BaseFrontController
{
    public function actionView($id)
    {
        /** @var Article $article */
        $article = Article::findOne($id);
        $article->increaseViewsCount();
        $article->save();

        return $this->render('view', ['article' => $article]);
    }

    public function actionCreate()
    {
        $article = new Article();
        if ($article->load($this->post()) && $article->save()) {
            return $this->redirect(['view', 'id' => $article->id]);
        }

        return $this->render('form', ['article' => $article]);
    }

    public function actionClearImages()
    {
        $articlesWithImages = Article::find()->hasImages()->all();

        $existencesImages = $this->getExistencesImages($articlesWithImages);

        $uploadedImages = $this->getUploadedImages();

        $this->deleteNonExitsImages($uploadedImages, $existencesImages);

        return $this->goBack();
    }

    /**
     * @param $articlesWithImages
     * @return array
     */
    public function getExistencesImages($articlesWithImages): array
    {
        $allowedImages = [];
        foreach ($articlesWithImages as $article) {
            $matches = [];
            preg_match_all('/!\[[^\[\]]*\]\(\/uploads\/([^\(\)]*\.(png|gif|jpg|jpeg))[^\(\)]*\)/ui', $article->content, $matches);
            if (count($matches) == 3 && isset($matches[1])) {
                $allowedImages = array_merge($allowedImages, $matches[1]);
            }

        }

        return $allowedImages;
    }

    /**
     * @return array
     */
    public function getUploadedImages(): array
    {
        $uploadedImages = scandir(Yii::getAlias('@webroot' . '/uploads/'));
        // remove . and .. from array
        unset($uploadedImages[0]);
        unset($uploadedImages[1]);

        return $uploadedImages;
    }

    /**
     * @param $uploadedImages
     * @param $existencesImages
     */
    public function deleteNonExitsImages($uploadedImages, $existencesImages)
    {
        $uploadsPath = Yii::getAlias('@webroot' . '/uploads/');
        foreach ($uploadedImages as $img) {
            if (!in_array($img, $existencesImages)) {
                unlink($uploadsPath . $img);
            }
        }
    }

    public function actionGetContent()
    {
        $articleId = $this->post('id');
        $content = Article::findOne($articleId)->content;

        return $content;
    }

    public function actionEdit($id)
    {
        /** @var Article $article */
        $article = Article::findOne($id);

        if ($article->load($this->post()) && $article->save()) {
            return $this->redirect(['view', 'id' => $article->id]);
        }

        return $this->render('form', ['article' => $article]);
    }

    public function actionDelete($id)
    {
        Article::deleteAll(['id' => $id]);

        return $this->redirect(['list']);
    }

    public function actionSaveContentAjax()
    {
        if (Request::isAjax()) {
            $id = Request::post('id');
            $article = Article::findOne($id);
            $article->content = Request::post('content');

            return $article->save();
        } else {
            return false;
        }

    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ar\Article;
use app\models\ar\ArticleSearch;
use app\models\ar\User;
use app\models\forms\{
    LoginForm, PasswordResetRequestForm, ResetPasswordForm
};
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Cookie;

class SiteController extends BaseFrontController
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionChangeThread($thread_id)
    {
        Yii::$app->response->cookies->add(new Cookie([
            'name'  => 'thread_id',
            'value' => $thread_id,
        ]));

        return $this->redirect('/');
    }

    /**
     * Render the homepage
     */
    public function actionIndex2()
    {
        $threadId = Yii::$app->view->params['thread_id'];
        $mainArticles = Article::find()->findMain($threadId)->all();
        $topArticles = Article::find()->findTop($threadId)->all();

        return $this->render('index2', ['mainArticles' => $mainArticles, 'topArticles' => $topArticles]);
    }

    /**
     * Render the homepage
     */
    public function actionIndex()
    {
        $threadId = Yii::$app->view->params['thread_id'];
        $searchModel = new ArticleSearch([
            'thread_id' => $threadId,
        ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionList($cat_id = null, $tag_id = null, $type_id = null)
    {
        $threadId = Yii::$app->view->params['thread_id'];

        $searchModel = new ArticleSearch([
            'thread_id'   => $threadId,
            'category_id' => $cat_id,
            'tag_id'      => $tag_id,
            'type_id'     => $type_id,

        ]);

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }


    /**
     * User login
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * User logout
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * User signup
     */
    public function actionSignup()
    {
        $user = new User(['scenario' => 'signup']);
        if ($user->load(Yii::$app->request->post()) && $user->save()) {
            Yii::$app->session->setFlash('user-signed-up');

            return $this->refresh();
        }

        if (Yii::$app->session->hasFlash('user-signed-up')) {
            return $this->render('signedUp');
        }

        return $this->render('signup', [
            'model' => $user,
        ]);
    }

    /**
     * Confirm email
     */
    public function actionConfirmEmail($token)
    {
        $user = User::find()->emailConfirmationToken($token)->one();

        if ($user !== null && $user->confirmEmail()) {
            Yii::$app->getUser()->login($user);

            return $this->goHome();
        }

        return $this->render('emailConfirmationFailed');
    }

    /**
     * Request password reset
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Reset password
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>

<div class="content-wrapper" style="margin-top: 50px;">

	<?= Breadcrumbs::widget(
		[
			'homeLink' => [
				'label' => 'Главная',
				'url'   => '/',
			],
			'links'    => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
		]
	); ?>
    <section class="content">
	    <?= $this->render('//meta/index') ?>
		<?= Alert::widget() ?>
		<?= $content ?>
    </section>
</div>

<aside class="control-sidebar control-sidebar-light">
</aside>
<div class='control-sidebar-bg'></div>
<footer class="main-footer">

</footer>

views/layouts/header.php
<?php


/* @var $this \yii\web\View */

use app\helpers\HTML;
use app\models\ar\User;

/* @var $content string */
?>
<?
$thread = \app\models\ar\SiteThread::findOne($this->params['thread_id']);
?>

<header class="main-header" style="position: fixed; width: 100%;">
	<?= Html::a('<span class="logo-mini">APP</span><span class="logo-lg">' . $thread->title . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>
    <nav class="navbar navbar-static-top" role="navigation">

        <!-- todoc temp commented -->
        <!-- <a href="#" class="toggle-sidebar-btn" data-toggle="offcanvas">
            <i class="fa fa-bars"></i>
        </a>-->
        <a href="#" class="toggle-sidebar-btn" data-toggle="categories">
            <i class="fa fa-arrow-circle-o-down"></i>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li>
					<?= HTML::a('<i class="fa fa-file-text-o"></i>', ['/article/create'], []); ?>
                </li>
                <li>
					<?= HTML::a('<i class="fa fa-superpowers"></i>', ['/article/clear-images'], []); ?>
                </li>
                <li class="dropdown user user-menu">
					<? if (Yii::$app->user->isGuest): ?>
                        <a href="<?= \yii\helpers\Url::to(['/site/login']) ?>">
                            <span class="hidden-xs">Авторизация</span>
                        </a>
					<? else: ?>
						<?
						/** @var User $user */
						$user = Yii::$app->user->identity;
						?>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="user-image"
                                 alt="User Image"/>
                            <span class="hidden-xs"><?= $user->username ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle"
                                     alt="User Image"/>

                                <p>
	                                <?= $user->username ?>
                                    <small>Киев, Украина</small>
                                </p>
                            </li>

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">Profile</a>
                                </div>
                                <div class="pull-right">
									<?= Html::a(
										'Выйти',
										['/site/logout'],
										['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
									) ?>
                                </div>
                            </li>
                        </ul>
					<? endif; ?>

                </li>
            </ul>
        </div>
    </nav>
</header>

views/layouts/left.php
<!-- todoc temp hiden-->
<aside class="main-sidebar" style="position: fixed; display: none">

    <section class="sidebar">
        <?
        /** @var \app\models\ar\Category[] $categories */
        $categories = \app\models\ar\Category::find()->thread(Yii::$app->view->params['thread_id'])->all();

        $categoriesMenu = [];
        $categoriesMenu[] = ['label' => 'Все категории', 'icon' => 'database  ', 'url' => ['/article/list', 'cat_id' => '']];
        foreach ($categories as $category) {
            $categoriesMenu[] = ['label' => $category->title, 'icon' => 'circle-o', 'url' => ['/article/list', 'cat_id' => $category->id]];
        }

        /** @var \app\models\ar\SiteThread[] $threads */
        $threads = \app\models\ar\SiteThread::find()->all();

        $threadsMenu = [];
        foreach ($threads as $thread) {
            $threadsMenu[] = ['label' => $thread->title, 'icon' => 'circle-o', 'url' => ['/site/change-thread', 'thread_id' => $thread->id]];
        }

        ?>

        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu'],
                'items'   => [
                    ['label' => 'Треды', 'icon' => 'bars', 'items' => $threadsMenu],
                    ['label' => 'Категории', 'icon' => 'bars', 'items' => $categoriesMenu],
//					['label' => 'Мета информация', 'icon' => 'hashtag', 'url' => ['/meta']],
                ],
            ]
        ) ?>

    </section>

</aside>

views/layouts/main-login.php
<?php

use app\assets\AppAsset;
use dmstr\web\AdminLteAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

AdminLteAsset::register($this);
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use app\assets\AppAsset;
use app\helpers\PHP;
use dmstr\helpers\AdminLteHelper;
use dmstr\web\AdminLteAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') {
	/**
	 * Do not use this code in your template. Remove it.
	 * Instead, use the code  $this->layout = '//main-login'; in your controller.
	 */
	echo $this->render(
		'main-login',
		['content' => $content]
	);
} else {
	AdminLteAsset::register($this);
	AppAsset::register($this);

	$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
	?>
	<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
		<?php $this->head() ?>
    </head>

	<?
	$sidebarOpened = PHP::isDefArr($_COOKIE, 'sidebarOpened', true);
	?>

    <body class=" <?= AdminLteHelper::skinClass() ?> <?= $sidebarOpened == 'true' ? '' : 'sidebar-collapse'; ?>">
	<?php $this->beginBody() ?>
    <div class="wrapper">
		<?= $this->render(
			'header.php',
			['directoryAsset' => $directoryAsset]
		) ?>

		<?= $this->render(
			'left.php',
			['directoryAsset' => $directoryAsset]
		)
		?>

		<?= $this->render(
			'content.php',
			['content' => $content, 'directoryAsset' => $directoryAsset]
		) ?>
    </div>

	<?php $this->endBody() ?>
    </body>
    </html>
	<?php $this->endPage() ?>
<?php } ?>