controllers/MetaController.php
<?php


namespace app\controllers;


use app\models\ar\Category;
use app\models\ar\SiteThread;
use app\models\ar\Tag;
use app\models\ar\Type;

class MetaController extends BaseFrontController
{

	public function actionIndex()
	{
		return $this->render('index');
	}

	public function actionCreateTag()
	{
		$tag = new Tag();
		if ($tag->load($this->post()) && $tag->save()) {
			return $this->goBack();
		}

		return $this->render('tag-form', ['tag' => $tag]);
	}

	public function actionEditTag($id)
	{
		$tag = Tag::findOne($id);
		if ($tag->load($this->post()) && $tag->save()) {
			return $this->goBack();
		}

		return $this->render('tag-form', ['tag' => $tag]);
	}

	public function actionCreateCategory()
	{
		$category = new Category();
		if ($category->load($this->post()) && $category->save()) {
			return $this->goBack();
		}

		return $this->render('category-form', ['category' => $category]);
	}

	public function actionEditCategory($id)
	{
		$category = Category::findOne($id);
		if ($category->load($this->post()) && $category->save()) {
			return $this->goBack();
		}

		return $this->render('category-form', ['category' => $category]);
	}

	public function actionCreateType()
	{
		$category = new Type();
		if ($category->load($this->post()) && $category->save()) {
			return $this->goBack();
		}

		return $this->render('type-form', ['type' => $category]);
	}

	public function actionEditType($id)
	{
		$category = Type::findOne($id);
		if ($category->load($this->post()) && $category->save()) {
			return $this->redirect('/');
		}

		return $this->render('type-form', ['type' => $category]);
	}

	public function actionCreateThread()
	{
		$category = new SiteThread();
		if ($category->load($this->post()) && $category->save()) {
			return $this->goBack();
		}

		return $this->render('thread-form', ['thread' => $category]);
	}

	public function actionEditThread($id)
	{
		$category = SiteThread::findOne($id);
		if ($category->load($this->post()) && $category->save()) {
			return $this->goBack();
		}

		return $this->render('thread-form', ['thread' => $category]);
	}

	public function actionDeleteTag($id)
	{
		Tag::deleteAll(['id' => $id]);

		return $this->goBack();
	}

	public function actionDeleteCategory($id)
	{
		Category::deleteAll(['id' => $id]);

		return $this->goBack();
	}

	public function actionDeleteThread($id)
	{
		/** @var SiteThread $thread */
		$thread = SiteThread::findOne($id);
		if ($thread->categoriesCount == 0) {
			SiteThread::deleteAll(['id' => $id]);
		}


		return $this->goBack();
	}

	public function actionDeleteType($id)
	{
		Type::deleteAll(['id' => $id]);

		return $this->goBack();
	}

}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ar\Article;
use app\models\ar\ArticleSearch;
use app\models\ar\User;
use app\models\forms\{
    LoginForm, PasswordResetRequestForm, ResetPasswordForm
};
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Cookie;

class SiteController extends BaseFrontController
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionChangeThread($thread_id)
    {
        Yii::$app->response->cookies->add(new Cookie([
            'name'  => 'thread_id',
            'value' => $thread_id,
        ]));

        return $this->redirect('/');
    }

    /**
     * Render the homepage
     */
    public function actionIndex2()
    {
        $threadId = Yii::$app->view->params['thread_id'];
        $mainArticles = Article::find()->findMain($threadId)->all();
        $topArticles = Article::find()->findTop($threadId)->all();

        return $this->render('index2', ['mainArticles' => $mainArticles, 'topArticles' => $topArticles]);
    }

    /**
     * Render the homepage
     */
    public function actionIndex()
    {
        $threadId = Yii::$app->view->params['thread_id'];
        $searchModel = new ArticleSearch([
            'thread_id' => $threadId,
        ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionList($cat_id = null, $tag_id = null, $type_id = null)
    {
        $threadId = Yii::$app->view->params['thread_id'];

        $searchModel = new ArticleSearch([
            'thread_id'   => $threadId,
            'category_id' => $cat_id,
            'tag_id'      => $tag_id,
            'type_id'     => $type_id,

        ]);

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }


    /**
     * User login
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * User logout
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * User signup
     */
    public function actionSignup()
    {
        $user = new User(['scenario' => 'signup']);
        if ($user->load(Yii::$app->request->post()) && $user->save()) {
            Yii::$app->session->setFlash('user-signed-up');

            return $this->refresh();
        }

        if (Yii::$app->session->hasFlash('user-signed-up')) {
            return $this->render('signedUp');
        }

        return $this->render('signup', [
            'model' => $user,
        ]);
    }

    /**
     * Confirm email
     */
    public function actionConfirmEmail($token)
    {
        $user = User::find()->emailConfirmationToken($token)->one();

        if ($user !== null && $user->confirmEmail()) {
            Yii::$app->getUser()->login($user);

            return $this->goHome();
        }

        return $this->render('emailConfirmationFailed');
    }

    /**
     * Request password reset
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Reset password
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

views/meta/category-form.php
<?
use app\helpers\HTML;
use kartik\form\ActiveForm;
use yii\web\View;

/** @var View $this */
/** @var \app\models\ar\Category $category */

$this->title = $category->title;
?>

<? $form = ActiveForm::begin(); ?>


<?= $form->field($category, 'title'); ?>

<?= HTML::submitButton('Сохранить', [
	'class' => 'btn btn-xs btn-default',
]) ?>

<? ActiveForm::end(); ?>

views/meta/index.php
<?

use app\helpers\HTML;
use app\helpers\PHP;
use app\models\ar\SiteThread;
use app\models\ar\Type;
use yii\web\View;

/** @var View $this */

$this->title = 'Мета информация';
//$this->params['breadcrumbs'][] = [
//	'label' => $this->title,
//];
?>
<?
$headerbarOpened = PHP::isDefArr($_COOKIE, 'headerbarOpened', true);
?>
<div class="row articles-meta">
    <div class="col-md-3">
        <h3>Теги</h3>
        <?
        $tags = \app\models\ar\Tag::find()->all();
        ?>
        <?= HTML::a('Создать тег', ['/meta/create-tag'], ['class' => 'btn btn-xs btn-success']); ?>
        <hr>
        <? foreach ($tags as $tag) : ?>
            <div>
                <?= HTML::a($tag->title . ' [' . $tag->articlesCount . ']', ['/site/list', 'tag_id' => $tag->id], ['class' => 'btn btn-xs btn-default']) ?>
                <?= HTML::a('<i class="fa fa-pencil"></i>',
                    ['/meta/edit-tag', 'id' => $tag->id], ['class' => 'btn btn-xs btn-default']) ?>
                <?= HTML::a('<i class="fa fa-times"></i>',
                    ['/meta/delete-tag', 'id' => $tag->id], ['class' => 'btn btn-xs btn-default js-ask-twice']) ?>
            </div>
        <? endforeach; ?>


    </div>

    <div class="col-md-3">

        <h3>Категории</h3>
        <?
        $categories = \app\models\ar\Category::find()->thread(Yii::$app->view->params['thread_id'])->all();
        ?>
        <?= HTML::a('Создать категорию', ['/meta/create-category'], ['class' => 'btn btn-xs btn-success']); ?>
        <hr>
        <? foreach ($categories as $category) : ?>
            <div>
                <?= HTML::a($category->title . ' [' . $category->articlesCount . ']', ['/site/list', 'cat_id' => $category->id], ['class' => 'btn btn-xs btn-default']) ?>
                <?= HTML::a('<i class="fa fa-pencil"></i>',
                    ['/meta/edit-category', 'id' => $category->id], ['class' => 'btn btn-xs btn-default']) ?>
                <? if ($category->articlesCount == 0): ?>
                    <?= HTML::a('<i class="fa fa-times"></i>',
                        ['/meta/delete-category', 'id' => $category->id], ['class' => 'btn btn-xs btn-default js-ask-twice']) ?>
                <? endif; ?>
            </div>
        <? endforeach; ?>


    </div>
    <div class="col-md-3">

        <h3>Типы</h3>
        <?
        /** @var Type[] $types */
        $types = Type::find()->all();
        ?>
        <?= HTML::a('Создать тип', ['/meta/create-type'], ['class' => 'btn btn-xs btn-success']); ?>
        <hr>
        <? foreach ($types as $type) : ?>
            <div>
                <?= HTML::a($type->title . ' [' . $type->getArticlesCount(true) . ']',
                    ['/site/list', 'type_id' => $type->id], ['class' => 'btn btn-xs btn-default']) ?>
                <?= HTML::a('<i class="fa fa-pencil"></i>',
                    ['/meta/edit-type', 'id' => $type->id], ['class' => 'btn btn-xs btn-default']) ?>
                <?= HTML::a('<i class="fa fa-times"></i>',
                    ['/meta/delete-type', 'id' => $type->id], ['class' => 'btn btn-xs btn-default js-ask-twice']); ?>
            </div>
        <? endforeach; ?>


    </div>
    <div class="col-md-3">

        <h3>Треды</h3>
        <?
        /** @var SiteThread[] $threads */
        $threads = SiteThread::find()->all();
        ?>
        <?= HTML::a('Создать тред', ['/meta/create-thread'], ['class' => 'btn btn-xs btn-success']); ?>
        <hr>
        <? foreach ($threads as $thread) : ?>
            <div>
                <?= HTML::a($thread->title . ' [' . $thread->articlesCount . ']' . ' [' . $thread->categoriesCount . ']',
                    ['/site/change-thread', 'thread_id' => $thread->id], ['class' => 'btn btn-xs btn-default']) ?>
                <?= HTML::a('<i class="fa fa-pencil"></i>',
                    ['/meta/edit-thread', 'id' => $thread->id], ['class' => 'btn btn-xs btn-default']) ?>
                <? if ($thread->categoriesCount == 0): ?>
                    <?= HTML::a('<i class="fa fa-times"></i>', ['/meta/delete-thread', 'id' => $thread->id], [
                        'class'             => 'btn btn-xs btn-default js-ask-twice',
                        'data-ask-question' => 'Вы уверены? Все категории и задачи к ним будут перенесены в тред по умолчанию!',
                    ]); ?>
                <? endif; ?>
            </div>
        <? endforeach; ?>

    </div>
</div>

views/meta/tag-form.php
<?
use app\helpers\HTML;
use kartik\form\ActiveForm;
use yii\web\View;

/** @var View $this */
/** @var \app\models\ar\Tag $tag */

$this->title = $tag->title;
?>

<? $form = ActiveForm::begin(); ?>


<?= $form->field($tag, 'title'); ?>

<?= HTML::submitButton('Сохранить', [
	'class' => 'btn btn-xs btn-default',
]) ?>

<? ActiveForm::end(); ?>

views/meta/thread-form.php
<?
use app\helpers\HTML;
use kartik\form\ActiveForm;
use yii\web\View;

/** @var View $this */
/** @var \app\models\ar\SiteThread $thread */

$this->title = $thread->title;
?>

<? $form = ActiveForm::begin(); ?>


<?= $form->field($thread, 'title'); ?>

<?= HTML::submitButton('Сохранить', [
	'class' => 'btn btn-xs btn-default',
]) ?>

<? ActiveForm::end(); ?>

views/meta/type-form.php
<?
use app\helpers\HTML;
use kartik\form\ActiveForm;
use yii\web\View;

/** @var View $this */
/** @var \app\models\ar\Type $type */

$this->title = $type->title;
?>

<? $form = ActiveForm::begin(); ?>


<?= $form->field($type, 'title'); ?>
<?= $form->field($type, 'icon'); ?>

<?= HTML::submitButton('Сохранить', [
	'class' => 'btn btn-xs btn-default',
]) ?>
    <div>
        <a href="http://fontawesome.io/icons/">http://fontawesome.io/icons/</a>
    </div>

<? ActiveForm::end(); ?>