controllers/ArticleController.php
<?php


namespace app\controllers;


use app\helpers\Request;
use app\models\ar\Article;
use app\models\ar\ArticleQuery;
use app\models\ar\Category;
use app\models\ar\Tag;
use app\models\ar\Type;
use Yii;
use yii\web\Controller;

class ArticleController extends BaseFrontController
{
    public function actionView($id)
    {
        /** @var Article $article */
        $article = Article::findOne($id);
        $article->increaseViewsCount();
        $article->save();

        return $this->render('view', ['article' => $article]);
    }

    public function actionCreate()
    {
        $article = new Article();
        if ($article->load($this->post()) && $article->save()) {
            return $this->redirect(['view', 'id' => $article->id]);
        }

        return $this->render('form', ['article' => $article]);
    }

    public function actionClearImages()
    {
        $articlesWithImages = Article::find()->hasImages()->all();

        $existencesImages = $this->getExistencesImages($articlesWithImages);

        $uploadedImages = $this->getUploadedImages();

        $this->deleteNonExitsImages($uploadedImages, $existencesImages);

        return $this->goBack();
    }

    /**
     * @param $articlesWithImages
     * @return array
     */
    public function getExistencesImages($articlesWithImages): array
    {
        $allowedImages = [];
        foreach ($articlesWithImages as $article) {
            $matches = [];
            preg_match_all('/!\[[^\[\]]*\]\(\/uploads\/([^\(\)]*\.(png|gif|jpg|jpeg))[^\(\)]*\)/ui', $article->content, $matches);
            if (count($matches) == 3 && isset($matches[1])) {
                $allowedImages = array_merge($allowedImages, $matches[1]);
            }

        }

        return $allowedImages;
    }

    /**
     * @return array
     */
    public function getUploadedImages(): array
    {
        $uploadedImages = scandir(Yii::getAlias('@webroot' . '/uploads/'));
        // remove . and .. from array
        unset($uploadedImages[0]);
        unset($uploadedImages[1]);

        return $uploadedImages;
    }

    /**
     * @param $uploadedImages
     * @param $existencesImages
     */
    public function deleteNonExitsImages($uploadedImages, $existencesImages)
    {
        $uploadsPath = Yii::getAlias('@webroot' . '/uploads/');
        foreach ($uploadedImages as $img) {
            if (!in_array($img, $existencesImages)) {
                unlink($uploadsPath . $img);
            }
        }
    }

    public function actionGetContent()
    {
        $articleId = $this->post('id');
        $content = Article::findOne($articleId)->content;

        return $content;
    }

    public function actionEdit($id)
    {
        /** @var Article $article */
        $article = Article::findOne($id);

        if ($article->load($this->post()) && $article->save()) {
            return $this->redirect(['view', 'id' => $article->id]);
        }

        return $this->render('form', ['article' => $article]);
    }

    public function actionDelete($id)
    {
        Article::deleteAll(['id' => $id]);

        return $this->redirect(['list']);
    }

    public function actionSaveContentAjax()
    {
        if (Request::isAjax()) {
            $id = Request::post('id');
            $article = Article::findOne($id);
            $article->content = Request::post('content');

            return $article->save();
        } else {
            return false;
        }

    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ar\Article;
use app\models\ar\ArticleSearch;
use app\models\ar\User;
use app\models\forms\{
    LoginForm, PasswordResetRequestForm, ResetPasswordForm
};
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Cookie;

class SiteController extends BaseFrontController
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionChangeThread($thread_id)
    {
        Yii::$app->response->cookies->add(new Cookie([
            'name'  => 'thread_id',
            'value' => $thread_id,
        ]));

        return $this->redirect('/');
    }

    /**
     * Render the homepage
     */
    public function actionIndex2()
    {
        $threadId = Yii::$app->view->params['thread_id'];
        $mainArticles = Article::find()->findMain($threadId)->all();
        $topArticles = Article::find()->findTop($threadId)->all();

        return $this->render('index2', ['mainArticles' => $mainArticles, 'topArticles' => $topArticles]);
    }

    /**
     * Render the homepage
     */
    public function actionIndex()
    {
        $threadId = Yii::$app->view->params['thread_id'];
        $searchModel = new ArticleSearch([
            'thread_id' => $threadId,
        ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionList($cat_id = null, $tag_id = null, $type_id = null)
    {
        $threadId = Yii::$app->view->params['thread_id'];

        $searchModel = new ArticleSearch([
            'thread_id'   => $threadId,
            'category_id' => $cat_id,
            'tag_id'      => $tag_id,
            'type_id'     => $type_id,

        ]);

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }


    /**
     * User login
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * User logout
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * User signup
     */
    public function actionSignup()
    {
        $user = new User(['scenario' => 'signup']);
        if ($user->load(Yii::$app->request->post()) && $user->save()) {
            Yii::$app->session->setFlash('user-signed-up');

            return $this->refresh();
        }

        if (Yii::$app->session->hasFlash('user-signed-up')) {
            return $this->render('signedUp');
        }

        return $this->render('signup', [
            'model' => $user,
        ]);
    }

    /**
     * Confirm email
     */
    public function actionConfirmEmail($token)
    {
        $user = User::find()->emailConfirmationToken($token)->one();

        if ($user !== null && $user->confirmEmail()) {
            Yii::$app->getUser()->login($user);

            return $this->goHome();
        }

        return $this->render('emailConfirmationFailed');
    }

    /**
     * Request password reset
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Reset password
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

views/article/form.php
<?php
/* @var yii\web\View $this */

/** @var Article $article */

use app\helpers\HTML;
use app\models\ar\Article;
use app\models\ar\Category;
use app\models\ar\Tag;
use app\models\ar\Type;
use kartik\form\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;

$title = $article->isNewRecord ? 'Новая статья' : $article->title;

$this->title = $title;


$category = $article->category;

$this->params['breadcrumbs'][] = [
	'label' => $category->title,
	'url'   => ['/article/list', 'cat_id' => $category->id],
];
$this->params['breadcrumbs'][] = [
	'label' => $this->title,
	'url'   => ['/article/view', 'id' => $article->id,],
];
$this->params['breadcrumbs'][] = [
	'label' => 'Редактировать',
]


?>


<? $form = ActiveForm::begin(); ?>

<?= HTML::submitButton('Сохранить', [
	'class' => 'btn btn-default',
	'style' => 'width: 100%',
]); ?>
<div class="article-edit-content">

    <div class="row">
        <div class="col-md-5">
			<?= $form->field($article, 'title'); ?>
        </div>
        <div class="col-md-4">
			<?= $form->field($article, 'category_id')->widget(Select2::className(), [
				'data'          => ArrayHelper::map(Category::find()->thread($this->params['thread_id'])->all(), 'id', 'title'),
				'options'       => ['placeholder' => 'Выберите категорию ...'],
				'pluginOptions' => [
					'allowClear' => true,
				],
			]) ?>
        </div>
        <div class="col-md-3">
			<?=
			$form->field($article, 'type_id')->widget(Select2::className(), [
				'data'          => ArrayHelper::map(Type::find()->all(), 'id', 'title'),
				'options'       => ['placeholder' => 'Выберите тип ...'],
				'pluginOptions' => [
					'allowClear' => true,
				],
			])
			?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
			<?=
			$form->field($article, 'tag_ids')->widget(Select2::className(), [
				'data'          => ArrayHelper::map(Tag::find()->all(), 'id', 'title'),
				'options'       => [
					'placeholder' => 'Выберите/создайте теги ...',
					'multiple'    => true,
				],
				'pluginOptions' => [
					'allowClear'      => true,
					'tags'            => true,
					'tokenSeparators' => [','],
				],
			])
			?>
        </div>
        <div class="col-md-4">
			<?= $form->field($article, 'priority')->radioList(
				['1' => 'Не важно', '2' => 'Норм', '3' => 'Важно']
			) ?>
        </div>
    </div>

	<?= $form->field($article, 'description')->textarea([
		'style' => 'height: 150px',
	]); ?>

    <div id="js-article-editor" data-id="<?= $article->id ?>">
		<?= \yii\helpers\Html::textarea('Article[content]', $article->content) ?>
    </div>

</div>

<? ActiveForm::end() ?>

views/article/view.php
<?

use app\assets\EditormdViewAsset;
use app\helpers\HTML;
use app\models\ar\Article;
//use app\models\enums\ArticleType;
use app\widgets\Box;
use yii\web\View;

/** @var View $this */

/** @var Article $article */
$this->title = $article->title;
EditormdViewAsset::register($this);

$category = $article->category;

$this->params['breadcrumbs'][] = [
	'label' => $category->title,
	'url'   => ['/article/list', 'cat_id' => $category->id],
];
$this->params['breadcrumbs'][] = [
	'label' => $this->title,
]

?>

<div class="article-view">
	<?
	$tagsButtons = '';
	foreach ($article->tags as $tag) {
		$tagsButtons .= HTML::a('#' . $tag->title, ['/article/list', 'tag_id' => $tag->id]);
	}
	?>
    <div class="article-view__header">
        <div class="pull-left">
            <span style="background-color: <?= $article->getPriorityColor() ?>">&nbsp;&nbsp;</span>
			<?= HTML::a($article->category->title . ': ', ['/article/list', 'cat_id' => $article->category_id]); ?>
			<?= HTML::a($article->title, ['/article/view', 'id' => $article->id]); ?>
			<?= HTML::a('[' . $article->type->title . ']', ['/article/list', 'type' => $article->type]); ?>
            <span class="article-view__views-count"><?= $article->views_count; ?></span>
        </div>
        <div class="pull-right">
			<?= HTML::a('<i class="fa fa-pencil"></i>', ['/article/edit', 'id' => $article->id]) ?>
			<?= HTML::a('<i class="fa fa-times"></i>', ['/article/delete', 'id' => $article->id], [
				'class' => 'js-ask-twice',
			]); ?>
        </div>
        <div class="clearfix"></div>
    </div>



    <div>
		<?= $tagsButtons ?>
    </div>
    <h4>Содержание</h4>
    <div class="markdown-body editormd-preview-container js-article-view__toc"></div>
    <div id="js-article-view">
        <textarea style="display:none;"><?= $article->content ?></textarea>
    </div>

    <a class="content-btn" href="#" data-toggle="modal" data-target=".article-view__toc-modal">
        <i class="fa fa-book"></i>
    </a>

    <div class="modal fade article-view__toc-modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Содержание</h4>
                </div>
                <div class="modal-body">
                    <div class="markdown-body editormd-preview-container js-article-view__toc"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                </div>
            </div>

        </div>
    </div>
</div>